# Generated by Django 4.2.19 on 2025-03-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldLatynUrl', models.CharField(max_length=255)),
                ('speakerId', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('shortDescription', models.TextField()),
                ('thumbnailUrl', models.CharField(max_length=255)),
                ('oldFileUrl', models.CharField(max_length=255)),
                ('filePath', models.CharField(max_length=255)),
                ('hasAudio', models.BooleanField(default=False)),
                ('hasFile', models.BooleanField(default=False)),
                ('language', models.CharField(default='kz', max_length=255)),
                ('year', models.CharField(default='0000', max_length=255)),
                ('addTime', models.PositiveIntegerField()),
                ('updateTime', models.PositiveIntegerField()),
                ('qStatus', models.PositiveSmallIntegerField()),
                ('html', models.TextField()),
            ],
        ),
    ]
